services:
    spring-app:
        container_name: spring-app
        build:
            context: .
            dockerfile: local/spring/Dockerfile
        ports:
            - "8090:8080"
        volumes:
            - ./MeteoDatas-SpringApp:/MeteoDatas-SpringApp
            - maven-cache:/root/.m2
        depends_on:
            - mongodb
        networks:
            - meteo
        tty: true
        restart: unless-stopped
    
    mongodb:
        image: mongo:8
        container_name: mongodb-local
        environment:
            MONGO_INITDB_ROOT_USERNAME : ${MONGODB_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD : ${MONGODB_PASSWORD}
            MONGO_INITDB_DATABASE : ${MONGODB_DATABASE}
        ports:
            - "27017:27017"
        volumes:
            - ./data/mongo:/data/db
        networks:
            - meteo
        restart: unless-stopped

networks:
    meteo:
      driver: bridge

volumes:
    maven-cache:
